game/urls.py
from django.conf.urls import url
from . import views

app_name = 'game'
urlpatterns = [
    url(r'^$', views.IndexView, name='index'),
    url(r'^create/$', views.CreateCharacter, name='create'),
    url(r'^delete/$', views.DeleteCharacter, name='delete'),
    url(r'^inventory/$', views.Inventory, name='inventory'),
    url(r'^pprofile/$', views.PlayerProfile, name='pprofile'),
    url(r'^cprofile/$', views.CharacterProfile, name='cprofile'),
    url(r'^game/$', views.Game, name='game'),
    url(r'^create/success/$', views.Success, name='success'),
    url(r'^create/failure/$', views.Failure, name='failure'),
    url(r'^store/$', views.StorePage, name='store'),
]

rpg/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from game import views as game_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^signup/$', game_views.signup, name='signup'),
    url(r'^', include('game.urls')),
]

game/models.py
from django.db import models
from django.contrib.auth.models import User


# define the character
class Character(models.Model):
    # set options for sex choice
    choices = ((
        'female',
        'Female'),
        ('male',
         'Male'),
        ('non-binary',
         'Non-Binary'))
    # user is foreign key to User
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=250)
    sex = models.CharField(max_length=10, choices=choices)
    created = models.DateField(auto_now_add=True)
    description = models.CharField(max_length=500)
    money = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    level = models.PositiveSmallIntegerField(default=0)
    hit_points = models.PositiveSmallIntegerField(default=10)
    experience = models.IntegerField(default=0)
    room = models.CharField(max_length=250, default='start_room')
    equipped_weapon = models.CharField(max_length=250, default='')
    equipped_item = models.CharField(max_length=250, default='')

# more readable output in admin and shell
    def __str__(self):
        return self.name + ' / ' + self.user.username


class CharacterItem(models.Model):
    character = models.ForeignKey(Character, on_delete=models.CASCADE)
    item = models.CharField(max_length=250)

    def __str__(self):
        return (self.character.user.username + ' / ' + self.character.name +
                ' / ' + self.item)


class CharacterKey(models.Model):
    character = models.ForeignKey(Character, on_delete=models.CASCADE)
    key = models.CharField(max_length=250)

    def __str__(self):
        return self.character + ' - ' + self.key


class CharacterObject(models.Model):
    character = models.ForeignKey(Character, on_delete=models.CASCADE)
    room = models.CharField(max_length=250)
    obj = models.CharField(max_length=250)
    is_locked = models.BooleanField(default=False)
    is_looted = models.BooleanField(default=True)

    def __str__(self):
        return self.character + ' - ' + self.room + '/' + self.obj


class CharacterWeapon(models.Model):
    character = models.ForeignKey(Character, on_delete=models.CASCADE)
    weapon = models.CharField(max_length=250)

    def __str__(self):
        return self.character + ' - ' + self.weapon


class CurrentCharacter(models.Model):
    user = models.CharField(max_length=250, unique=True)
    character = models.CharField(max_length=250)

    def __str__(self):
        return self.character + ' - ' + self.user


class Item(models.Model):
    name = models.CharField(max_length=250)
    description = models.CharField(max_length=500)
    stat_affected = models.CharField(max_length=20)
    effect_amt = models.PositiveSmallIntegerField()
    cost = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    sell = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)

    def __str__(self):
        return self.name


class Key(models.Model):
    name = models.CharField(max_length=250)
    description = models.CharField(max_length=500)
    room = models.CharField(max_length=250)
    obj = models.CharField(max_length=250)

    def __str__(self):
        return self.name


class Object(models.Model):
    name = models.CharField(max_length=250)
    description = models.CharField(max_length=500)

    def __str__(self):
        return self.name


class ObjectChild(models.Model):
    obj = models.ForeignKey(Object, on_delete=models.CASCADE)
    child = models.CharField(max_length=250)

    def __str__(self):
        return self.name + ' / ' + self.child


class ObjectItem(models.Model):
    obj = models.ForeignKey(Object, on_delete=models.CASCADE)
    item = models.CharField(max_length=250)

    def __str__(self):
        return self.obj + ' / ' + self.item


class Room(models.Model):
    choices = (
        ('combat', 'combat'),
        ('store', 'store'),
        ('spawn', 'spawn'),
        ('basic', 'basic'),
    )
    name = models.CharField(max_length=250)
    dark_description = models.CharField(max_length=500)
    light_description = models.CharField(max_length=500)
    room_type = models.CharField(max_length=50, choices=choices)

    def __str__(self):
        return self.name + ' - ' + self.room_type


class RoomWallObject(models.Model):
    choices = (
        ('north', 'north'),
        ('south', 'south'),
        ('east', 'east'),
        ('west', 'west'),
        ('up', 'up'),
        ('down', 'down'),
    )
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    wall = models.CharField(max_length=10, choices=choices)
    obj1 = models.CharField(max_length=250, default='')
    obj2 = models.CharField(max_length=250, default='')
    obj3 = models.CharField(max_length=250, default='')
    obj4 = models.CharField(max_length=250, default='')
    obj5 = models.CharField(max_length=250, default='')


class Store(models.Model):
    name = models.CharField(max_length=250)
    money = models.DecimalField(max_digits=10, decimal_places=2)
    room = models.CharField(max_length=250)

    def __str__(self):
        return self.name + ' - ' + self.room + ' $' + str(self.money)


class StoreInventory(models.Model):
    store = models.ForeignKey(Store, on_delete=models.CASCADE)
    item = models.CharField(max_length=250)

    def __str__(self):
        return str(self.store) + ' - ' + self.item


class Weapon(models.Model):
    name = models.CharField(max_length=250)
    description = models.CharField(max_length=500)
    damage = models.PositiveSmallIntegerField()
    accuracy = models.DecimalField(max_digits=5, decimal_places=2)

    def __str__(self):
        return self.name + ' DMG: ' + str(self.damage)

game/forms.py
from django import forms


class UserRegistrationForm(forms.Form):
    username = forms.CharField(
        required=True,
        label='Username',
        max_length=32
    )
    email = forms.CharField(
        required=True,
        label='Email',
        max_length=250,
    )
    password = forms.CharField(
        required=True,
        label='Password',
        max_length=32,
        widget=forms.PasswordInput()
    )


class CharacterCreation(forms.Form):
    name = forms.CharField(
        max_length=32,
        required=True,
        label='Character Name')
    sex = forms.ChoiceField(
        label='Sex',
        required=True,
        choices=((
            'female',
            'Female'),
            ('male',
             'Male'),
            ('non-binary',
             'Non-Binary'))
        )

game/views.py
# django and python import
from django import forms
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import render

# model, forms, and functions import
from .forms import CharacterCreation, UserRegistrationForm
from game import functions
from .models import Character
from .models import CharacterItem
from .models import CurrentCharacter
from .models import Item
from .models import Store
from .models import StoreInventory

# for the date you can use datetime.date.today() or
# datetime.datetime.now().date()
# for the time you can use datetime.datetime.now().time()


def IndexView(request):
    template = 'game/index.html'
    context = functions.FetchContext(request)
    return render(request, template, context)


def signup(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            userObj = form.cleaned_data
            username = userObj['username']
            email = userObj['email']
            password = userObj['password']
            if not (User.objects.filter(username=username).exists() or
                    User.objects.filter(email=email).exists()):
                User.objects.create_user(username, email, password)
                user = authenticate(username=username, password=password)
                login(request, user)
                return HttpResponseRedirect('/')
            else:
                raise forms.ValidationError('Looks like a username with that\
                                            email or password already exists')
    else:
        form = UserRegistrationForm()
    return render(request, 'registration/signup.html', {'form': form})


@login_required
def CreateCharacter(request):
    if request.method == 'POST':
        form = CharacterCreation(request.POST)
        if form.is_valid():
            # process form data
            user = request.user
            if not (Character.objects.filter(name=form.cleaned_data['name'])
                    .exists()):
                name = form.cleaned_data['name']
                sex = form.cleaned_data['sex']
                Character.objects.create(user=user, name=name, sex=sex)
                if not CurrentCharacter.objects.filter(user=user.username):
                    obj = Character.objects.get(name=name)
                    CurrentCharacter.objects.create(user=user.username,
                                                    character=obj.name)
                return HttpResponseRedirect('success')
            else:
                return HttpResponseRedirect('failure')
        else:
            return messages.error(request, 'Error')
    else:
        context = functions.FetchContext(request)
        form = CharacterCreation()
        context['form'] = form
        template = 'game/create.html'
        return render(request, template, context)


@login_required
def DeleteCharacter(request):
    if request.method == 'POST':
        context = functions.FetchContext(request)
        user = User.objects.get(username=context['user'])
        characters = Character.objects.filter(user=user).order_by('created')
        template = 'game/delete.html'
        name = request.POST.get('select_character')
        character = Character.objects.get(name=name)
        character.delete()
        try:
            active = CurrentCharacter.objects.get(
                user=context['user'].username)
            active.delete()
        except:
            pass
        context['characters'] = characters
        return render(request, template, context)
    else:
        context = functions.FetchContext(request)
        user = User.objects.get(username=context['user'])
        characters = Character.objects.filter(user=user).order_by('created')
        template = 'game/delete.html'
        context['characters'] = characters
        return render(request, template, context)


@login_required
def PlayerProfile(request):
    user = request.user
    characters = Character.objects.filter(user=user)
    user_info = User.objects.get(username=user.username)
    template = 'game/pprofile.html'
    context = functions.FetchContext(request)
    context['characters'] = characters
    context['user_info'] = user_info
    return render(request, template, context)


@login_required
def CharacterProfile(request):
    if request.method == 'POST':
        user = request.user
        name = request.POST.get('select_character')
        character = Character.objects.get(name=name)
        if CurrentCharacter.objects.get(user=user.username):
            CurrentCharacter.objects.get(user=user.username).delete()
            current_character = CurrentCharacter.objects.create(
                user=user.username, character=character.name)
            characters = Character.objects.filter(user=user).order_by(
                'created')
            template = 'game/cprofile.html'
            context = functions.FetchContext(request)
            context['active'] = current_character
            context['characters'] = characters
            return render(request, template, context)
        else:
            current_character = CurrentCharacter.objects.create()
            current_character.user = user.username
            current_character.character = character.name
            current_character.save()
            template = 'game/cprofile.html'
            characters = Character.objects.filter(user=user).order_by(
                'created')
            context = functions.FetchContext(request)
            context['active'] = current_character
            context['characters'] = characters
            return render(request, template, context)
    else:
        user = request.user
        template = 'game/cprofile.html'
        characters = Character.objects.filter(user=user).order_by(
            'created')
        try:
            active = CurrentCharacter.objects.get(user=user.username)
        except:
            active = Character.objects.get(user=user).first()
        context = functions.FetchContext(request)
        context['characters'] = characters
        context['active'] = active
    return render(request, template, context)


@login_required
def Game(request):
    template = 'game/game.html'
    context = functions.FetchContext(request)
    return render(request, template, context)


@login_required
def Success(request):
    template = 'game/success.html'
    context = functions.FetchContext(request)
    return render(request, template, context)


@login_required
def Failure(request):
    template = 'game/failure.html'
    context = functions.FetchContext(request)
    return render(request, template, context)


@login_required
def Inventory(request):
    if request.method == 'POST':
        # get username from request
        user = request.user
        # get current character object
        try:
            name = CurrentCharacter.objects.get(user=user.username)
            character = Character.objects.get(name=name.character)
        except:
            character = Character.objects.filter(user=user).first()
        # get item button clicked and its object
        item_name = request.POST.get('item_name')
        item = Item.objects.get(name=item_name)
        if character.equipped_item == item.name:
            character.equipped_item = ''
            character.save()
        else:
            character.equipped_item = item_name
            character.save()
        template = 'game/inventory.html'
        try:
            name = CurrentCharacter.objects.get(user=user.username)
            character = Character.objects.get(name=name.character)
        except:
            character = Character.objects.filter(user=user).first()
        active_char_items = CharacterItem.objects.filter(
            character=character)
        items_list = []
        for i in active_char_items:
            item = i.item
            items_list.append(item)
        items = Item.objects.filter(name__in=items_list)
        context = functions.FetchContext(request)
        context['items'] = items
        context['character'] = character
        return render(request, template, context)
    else:
        user = request.user
        try:
            active = CurrentCharacter.objects.get(user=user.username)
            character = Character.objects.get(name=active.character)
        except:
            character = Character.objects.filter(user=user).first()
        template = 'game/inventory.html'
        active_char_items = CharacterItem.objects.filter(
            character=character)
        items_list = []
        for i in active_char_items:
            item = i.item
            items_list.append(item)
        items = Item.objects.filter(name__in=items_list)
        context = functions.FetchContext(request)
        context['items'] = items
        context['character'] = character
        return render(request, template, context)


@login_required
def StorePage(request):
    if request.method == 'POST' and 'buy' in request.POST:
        # display store items
        fetch = functions.FetchContext(request)
        context = functions.FetchItemLists(request, fetch)
        context['method'] = 'buy'
        template = 'game/store.html'
        return render(request, template, context)
    elif request.method == 'POST' and 'sell' in request.POST:
        # display character items
        fetch = functions.FetchContext(request)
        context = functions.FetchItemLists(request, fetch)
        template = 'game/store.html'
        context['method'] = 'sell'
        return render(request, template, context)
    elif request.method == 'POST' and 'buy_item' in request.POST:
        # buy item from the store
        # get user and active character information
        user = request.user

game/templates/game/base.html
<html lang="en">
    <head>
        <title>The Arrival</title>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'game/main.css' %}?v='text'"/>
        <script src="{% static 'game/main.js' %}"></script>
    </head>
    <body>
        <div class="wrapper">
            <div class="title_text">
                <h1>The Arrival</h1>
            </div>
            <div class="nav_bar">
                {% if user.is_authenticated %}
                    <p id="logout_button"><a href="{% url 'logout' %}" class="button">Log Out</a></p>
                    <p id="logout_button"><a href="{% url 'game:index' %}" class="button">Home</a></p>
                {% else %}
                    <p id="logout_button"><a href="{% url 'game:index' %}" class="button">Home</a></p>
                    <p id="login_button"><a href="{% url 'login' %}" class="button">Log In</a></p>
                    <p id="signup_button"><a href="{% url 'signup' %}" class="button">Sign Up</a></p>
                {% endif %}
            </div>
            <div class="body">
                <div class="welcome">
                    {% if user.is_authenticated %}
                        <p>Welcome back, {{ user.username }}!</p>
                    {% else %}
                        <p>Welcome, Guest!</p>
                    {% endif %}
                </div>
                <div class="side_bar">
                    {% if user.is_authenticated %}
                        <p><a href="{% url 'game:create' %}" class="button">Create A Character</a></p>
                        <p><a href="{% url 'game:delete' %}" class="button">Delete A Character</a></p>
                        <p><a href="{% url 'game:inventory' %}" class="button">Active Character Inventory</a></p>
                        <p><a href="{% url 'game:pprofile' %}" class="button">Player Profile</a></p>
                        <p><a href="{% url 'game:cprofile' %}" class="button">Character Profile</a></p>
                        {% if store %}
                            <p><a href="{% url 'game:store' %}" class="button">Visit Store</a></p>
                        {% endif %}
                        <p><a href="{% url 'game:game' %}" class="button">Play Arrival</a></p>
                    {% else %}
                        <p><a href="{% url 'login' %}" class="button">Log In</a></p>
                        <p><a href="{% url 'signup' %}" class="button">Sign Up</a></p>
                    {% endif %}

                </div>
            </div>
            <div class="stats_bar">
                <p id="users"><strong>Users Recently Online:</strong></p>
                {% for user in users %}
                    {% if users|length > 1 %}
                        <p id="username">{{ user.username }},</p>
                    {% else %}
                        <p id="username">{{ user.username }}</p>
                    {% endif %}
                {% endfor %}
                <hr />
                <p id="users"><strong>Existing Characters:</strong></p>
                <p id="username">{{ chars }}</p>
                <hr />
                <p id="it_is_now"><strong>Current Game Time:  </strong></p>
                <p id="time">{% now "DATETIME_FORMAT" %}</p>
                <p id="total_money"><strong>Players Total Wealth: </strong></p>
                <p id="amount">${{ total_money_found }}</p>
            </div>
            <div class="block_content">
                {% block content %}
                {% endblock %}
            </div>
        </div>
  </body>
</html>

game/templates/game/cprofile.html
{% extends "game/base.html" %}

{% block content %}
<h2 id="cp_header">Character Profile</h2>
<div class="char_display">
    <div class="char_field">
        {% for character in characters %}
            {% if character.name in active.character %}
                <div class="active">
                    <p><strong>Active Character</strong></p>
                </div>
            {% endif %}
            <div class="char_line_1">
                <p id="name"><strong>Name:</strong> {{ character.name }} &nbsp&nbsp&nbsp&nbsp&nbsp ${{ character.money }}</p>
                <p><strong>Level:</strong> {{ character.level }}</p>
                <p id="exp"><strong>Experience:</strong> {{ character.experience }}</p>
            </div>
            <div class="char_line_2">
                <p id="sex"><strong>Sex:</strong> {{ character.sex }}</p>
                <p><strong>Room:</strong> {{ character.room }}</p>
                <p id="hit_points"><strong>Hit Points:</strong> {{ character.hit_points }}</p>
            </div>
            <div class="char_line_3">
                <p id="item"><strong>Equipped Item:</strong> {{ character.equipped_item }}</p>
                <p><strong>Equipped Weapon:</strong> {{ character.equipped_weapon }}</p>
                <p id="created"><strong>Date Created:</strong> {{ character.created }}</p>
            </div>
            <div class="char_line_4">
                {% if character.name in active.character %}
                {% else %}
                    <form method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="select_character" value="{{ character.name }}" />
                        <button class="button" type="submit">Make Active</button>
                    </form>
                {% endif %}
            </div>
            <hr />
        {% endfor %}
    </div>
</div>
{% endblock %}

game/templates/game/create.html
{% extends "game/base.html" %}

{% block content %}
<div class="signup">
    <h2>Create A Character</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
</div>
{% endblock %}

game/templates/game/delete.html
{% extends "game/base.html" %}

{% block content %}
<div class="index_text">
    <h2 id="del_header">Delete Characters</h2>
    <h4 id="del_header2">This is not reversible!</h4>
    {% for character in characters %}
        <form method="POST">
            {% csrf_token %}
            <input type="hidden" name="select_character" value="{{ character.name }}" />
            <button class="button" type="submit">{{ character.name }}</button>
        </form>
    {% endfor %}
</div>
{% endblock %}

game/templates/game/failure.html
{% extends "game/base.html" %}

{% block content %}
<div class="signup">
    <p>
        That character already exists.
        <a href="/">Home</a>
    </p>
</div>
{% endblock %}

game/templates/game/index.html
{% extends "game/base.html" %}

{% block content %}
<div class="index_text">
    <p>Arrival is a text based rpg created with Python, using the framework Django.<br />
    Sign up for an account and create a character! In Arrival, you will explore<br />
    the area around you discovering secrets and items along the way. Will you<br />
    survive the Arrival?</p>
</div>
{% endblock %}

game/templates/game/inventory.html
{% extends "game/base.html" %}

{% block content %}
    <div class="for_loop">
        <p><strong>{{ character.name }}</strong> currently has ${{ character.money }}</p>
        {% for item in items %}
            <div class="item_col1">
                <div class="item_row">
                    <p>Name: {{ item.name }} &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp  Stat: {{ item.stat_affected }} &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp  Value: {{ item.effect_amt }}</p>
                    {% if character.equipped_item == item.name %}
                    <form method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="item_name" value="{{ item.name }}" />
                        <button class="button" type="submit">Unequip Item</button>
                    </form>
                    {% else %}
                        <form method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="item_name" value="{{ item.name }}" />
                            <button class="button" type="submit">Equip Item</button>
                        </form>
                    {% endif %}
                </div>
            </div>
            <hr width=80%/>
        {% endfor %}
    </div>
{% endblock %}

game/templates/game/pprofile.html
{% extends "game/base.html" %}

{% block content %}
    <div class="player_profile">
        <h2>Player Profile</h2>
        <div class="user_top_1">
            <p><strong>User Name:  </strong>{{ user_info.username }}</p>
        </div>
        <div class="user_top_2">
            <p><strong>Arrival Date:  </strong>{{ user_info.date_joined }}</p>
        </div>
        <div class="user_row_2_1">
            <p><strong>Active Character:  </strong>{{ active.character }}</p>
        </div>
    </div>
{% endblock %}

game/templates/game/store.html
{% extends "game/base.html" %}

{% block content %}
    <div class="header2">
        <p><h2>Welcome to {{ store.name }}</h2></p>
        <p>{{ store.name }} currently has ${{ store.money }}.</p>
        <p>{{ character.name }} currently has ${{ character.money }}</p>
        <hr />
    </div>
    {% if method == 'get' %}
        <form method="POST">
            {% csrf_token %}
            <input type="hidden" name="buy" value="buy" />
            <button class="button" type="submit">I would like to buy.</button>
        </form>
        <form method="POST">
            {% csrf_token %}
            <input type="hidden" name="sell" value="sell" />
            <button class="button" type="submit">I would like to sell.</button>
        </form>
    {% elif method == 'buy' %}
        <div class="for_loop">
            {% for item in s_items %}
                {% if item.cost <= character.money %}
                    <div class="item_col1">
                        <div class="item_row">
                            <p class="f_left">Name: {{ item.name }}</p>
                            <p class="f_right">Effect: {{ item.stat_affected }} +{{ item.effect_amt }}</p>
                            <form method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="buy_item" value="{{ item.name }}" />
                                <button class="button" type="submit">Purchase for ${{ item.cost }}</button>
                            </form>
                        </div>
                        <hr width=80%/>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    {% elif method == 'sell' %}
        <div class="for_loop">
            {% for item in c_items %}
                {% if item.sell <= store.money %}
                    <div class="item_col1">
                        <div class="item_row">
                            <p class="f_left">Name: {{ item.name }}</p>
                            <p class="f_right">Effect: {{ item.stat_affected }} +{{ item.effect_amt }}</p>
                            <form method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="sell_item" value="{{ item.name }}" />
                                <button class="button" type="submit">Sell for ${{ item.sell }}</button>
                            </form>
                        </div>
                    </div>
                    <hr width=80%/>
                {% endif %}
            {% endfor %}
        </div>
    {% endif %}
    {% if method != 'get' %}
        <div class="center">
            <form method="POST">
                {% csrf_token %}
                <input type="hidden" name="buy" />
                <button class="button" type="submit">I would like to buy.</button>
            </form>
            <form method="POST">
                {% csrf_token %}
                <input type="hidden" name="sell" />
                <button class="button" type="submit">I would like to sell.</button>
            </form>
        </div>
    {% endif %}
{% endblock %}

game/templates/game/success.html
{% extends "game/base.html" %}

{% block content %}
<div class="signup">
    <p>
        You have successfully created a character.
        <a href="/">Home</a>
    </p>
</div>
{% endblock %}